### ISSUE TITLE
build error: two typos? inptut -> input, stirde -> stride

### ISSUE THREAD

**Issue by mewmew** [marty1885/tmviz#2]
I tried building etaler/tmviz-etaler@263de7f8abf6c7c2249f9766a0fe25e2e849a0aa but ran into the following build error:

```
/usr/include/Etaler/Core/Shape.hpp: In function ‘et::Shape et::convResultShape(const et::Shape&, const et::Shape&, const et::Shape&)’:
/usr/include/Etaler/Core/Shape.hpp:181:2: error: ‘inptut’ was not declared in this scope; did you mean ‘input’?
  181 |  assert(inptut.size() == kernel.size());
      |  ^~~~~~
/usr/include/Etaler/Core/Shape.hpp:182:2: error: ‘stirde’ was not declared in this scope; did you mean ‘stride’?
  182 |  assert(inptut.size() == stirde.size());
      |  ^~~~~~
/home/u/Desktop/etaler_p
```

P.S. I intended to report this issue to the https://github.com/etaler/tmviz-etaler repository, but that repo had issues disabled.

**Comment by mewmew** [comment]
With https://github.com/etaler/Etaler/pull/136 merged, tmviz builds and runs successfully. Wow, really cool to see the HTM algorithms come to life!

Great work @marty1885!

![screenshot_2020-03-21_00:38:15](https://user-images.githubusercontent.com/1414531/77213794-6cf50d00-6b0c-11ea-8ff8-c4cca5731f01.png)

**Comment by marty1885** [comment]
@mewmew Thanks a lot! I've no idea why issues are disabled in tmviz-etaler. I've enabled it now.

I've discover the problem a few days back - it didn't show up as I don't make debug builds often. And the fix  (https://github.com/marty1885/Etaler/commit/90b5b62abcab196c35e94a3c14985bb62361d18d) hasn't been merged to master. Anyway, thanks a lot for looking into the codebase!
